# A github workflow which runs the pre-commit configured for the project.
name: generate-rss

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "*.py"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Get Changed Files
        id: files
        run: |
          files=$(git diff --name-only refs/remotes/origin/${{ github.base_ref }} | sed 's/ /\\ /g'| xargs)
          echo "Changed files: '${files}'"
          echo "list=${files}" >> $GITHUB_OUTPUT

      - name: Generate RSS, HTML and JSON
        run: |
          mkdir -p public
          task generate

      - name: Publish to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
